// Copyright (C) 2026 Rakshan Shetty
// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * What a reference file weighs and hashes to, without reading it.
 *
 * A skill listing carries `contentSha256` and `byteSize` — the fields that let
 * a client skip a fetch — and both are derived from every reference file's
 * bytes. Computing them the obvious way re-reads the whole bundled reference
 * set (125,870 bytes across 23 files) on every `GET /api/skills`, which is
 * exactly the cost the lazy `content` getter was introduced to remove.
 *
 * Bundled reference content is fixed when the package is built, so the digest
 * can be too: `scripts/copy-assets.mjs` writes {@link DIGEST_MANIFEST} next to
 * the skills at build time and a listing reads that instead of the files.
 */
import { createHash } from 'node:crypto';
import { readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import type { SkillReference } from './catalog.js';

/** Size and hash of one file's text, as `summarize()` needs them. */
export interface FileDigest {
  /** UTF-8 bytes of the file's decoded text. */
  bytes: number;
  /** sha256 of that text, hex. */
  sha256: string;
}

/**
 * Bytes of reference *content* this process has actually pulled off disk.
 *
 * Exported because it is the only way to state the guarantee as a test rather
 * than as a comment: a listing must not move `bytes`. See
 * test/skill-listing-cost.test.ts.
 */
export const referenceReads = { bytes: 0, files: 0 };

/**
 * Read a reference file, counting what it cost, or `null` if the read FAILED.
 *
 * The two are different answers: a file that is really empty is a fact about
 * the skill, and an EACCES is a fact about this moment. Only the first may be
 * remembered — see {@link lazyReference}.
 */
function tryReadReferenceText(path: string): string | null {
  let text: string;
  try { text = readFileSync(path, 'utf-8'); } catch { return null; }
  referenceReads.bytes += Buffer.byteLength(text, 'utf8');
  referenceReads.files += 1;
  return text;
}

/**
 * Read a reference file, counting what it cost.
 *
 * A file that has become unreadable since its directory was listed reads as
 * empty rather than throwing: a caller in the middle of an install cannot do
 * anything useful with an exception from a property access.
 */
export function readReferenceText(path: string): string {
  return tryReadReferenceText(path) ?? '';
}

/** Digest of text already in memory — no file involved. */
export function digestOf(text: string): FileDigest {
  return {
    bytes: Buffer.byteLength(text, 'utf8'),
    sha256: createHash('sha256').update(text, 'utf8').digest('hex'),
  };
}

/**
 * The build-generated manifest, written beside the skills it describes so it
 * travels with them into `dist/` and into the npm tarball. Regenerated by
 * `scripts/copy-assets.mjs` on every `npm run build`.
 */
export const DIGEST_MANIFEST = 'digests.json';

/** One manifest row. `size` is the on-disk file size, which is what validates
 *  the row; `bytes`/`sha256` describe the DECODED text, which is what a caller
 *  wants (they differ from `size` for a file with a BOM or a bad sequence). */
interface ManifestEntry { size: number; bytes: number; sha256: string }

/** Parsed manifests, keyed by the directory they came from. */
const manifests = new Map<string, Map<string, ManifestEntry>>();

function manifestFor(dir: string): Map<string, ManifestEntry> {
  const hit = manifests.get(dir);
  if (hit) return hit;
  const out = new Map<string, ManifestEntry>();
  try {
    const parsed: unknown = JSON.parse(readFileSync(join(dir, DIGEST_MANIFEST), 'utf-8'));
    const files = (parsed as { version?: unknown; files?: unknown } | null)?.version === 1
      ? (parsed as { files?: unknown }).files
      : undefined;
    // Built into a Map, so a key like `__proto__` in the file is just a key.
    for (const [key, v] of Object.entries((files ?? {}) as Record<string, unknown>)) {
      const e = v as Partial<ManifestEntry>;
      if (typeof e?.size !== 'number' || typeof e.bytes !== 'number' || typeof e.sha256 !== 'string') continue;
      out.set(key, { size: e.size, bytes: e.bytes, sha256: e.sha256 });
    }
  } catch { /* no manifest, or an unusable one: every lookup falls back to reading */ }
  manifests.set(dir, out);
  return out;
}

/** Forget the parsed manifests. For tests that write one and read it back. */
export function clearDigestCache(): void { manifests.clear(); }

/**
 * What `key` (a path relative to `dir`) weighs and hashes to, or null when the
 * manifest cannot say — in which case only reading the file can.
 *
 * The manifest row is trusted only while the file's SIZE still matches it.
 * Size, not mtime: mtimes are rewritten by `npm pack`/install and by every
 * checkout, so an mtime check would miss the manifest on exactly the machines
 * that only ever consume it. A mismatch — an edited bundled reference between
 * builds — falls back to reading the file and hashing what is really there, so
 * the answer is never wrong, only occasionally expensive.
 *
 * What that leaves: an edit that keeps the byte count identical and is never
 * followed by a build. Bundled skills are read-only by contract and change
 * only through a release, and a release runs `npm run build`, which rewrites
 * the manifest from the files themselves.
 */
export function manifestDigest(dir: string, key: string, path: string): FileDigest | null {
  const entry = manifestFor(dir).get(key);
  if (!entry) return null;
  try {
    if (statSync(path).size === entry.size) return { bytes: entry.bytes, sha256: entry.sha256 };
  } catch { /* unreadable now: the caller reads it, and reports it as empty, as it always has */ }
  return null;
}

/** {@link manifestDigest}, falling back to reading the file. */
export function fileDigest(dir: string, key: string, path: string): FileDigest {
  return manifestDigest(dir, key, path) ?? digestOf(readReferenceText(path));
}

/**
 * A reference file that is named now and read only if something asks for it.
 *
 * Every listing used to pay for every byte of every reference file: 137,923
 * bytes read and discarded per catalog load, to render a list that carries only
 * the paths. `install` genuinely needs the contents, so the read moved to the
 * point of use rather than being deleted.
 *
 * `digest` is the same idea one level up: a listing needs the file's size and
 * hash, not its text, and the build writes both into a manifest so asking for
 * them costs a `stat`. See ./digests.ts.
 *
 * Synchronous because `content` is a plain string on the interface, and making
 * it a promise would push async into every caller for a read that is a few KB
 * of packaged, local file — the same read the eager version already did, just
 * later and only when needed. Cached, so it happens at most once per process.
 *
 * A file that has become unreadable since the directory was listed reads as
 * empty rather than throwing: a caller in the middle of an install cannot do
 * anything useful with an exception from a property access. That empty answer
 * is NOT cached, because a failure is not a reading: caching it would turn one
 * transient EACCES during a listing into a zero-byte reference file written by
 * every later install in this process — reported as `references: N`, with a
 * content hash taken over the emptiness. Only a read that succeeded is
 * remembered, so the next ask retries and gets the real bytes.
 */
export function lazyReference(dir: string, id: string, rel: string): SkillReference {
  const path = join(dir, id, rel);
  let cached: string | undefined;
  const read = (): string => {
    if (cached !== undefined) return cached;
    const text = tryReadReferenceText(path);
    if (text === null) return '';   // failed: answer empty, remember nothing
    return (cached = text);
  };
  return {
    rel,
    get content(): string { return read(); },
    // The same read, without the lossy `?? ''`. A writer asks through this so
    // that "unreadable" can be reported as such instead of being written out as
    // an empty file whose digest still claims the manifest's bytes.
    tryContent(): string | null {
      if (cached !== undefined) return cached;
      const text = tryReadReferenceText(path);
      return text === null ? null : (cached = text);
    },
    // Text already in hand is the truth; the manifest is only a way to skip the
    // read, never a second source of it. A manifest miss reads through `read`
    // rather than separately, so the miss costs one read and not one per ask.
    get digest(): FileDigest {
      if (cached !== undefined) return digestOf(cached);
      return manifestDigest(dir, `${id}/${rel}`, path) ?? digestOf(read());
    },
  };
}
